### ISSUE TITLE
About Environment

### ISSUE THREAD

**Issue by AmingWu** [Meowuu7/GeneOH-Diffusion#5]
Dear Authors,

My environment is torch 2.0.1+cu117. Could I use this environment to run your code?

Thanks.

**Comment by Meowuu7** [comment]
Hi @AmingWu ,

I've never tried this environment before. It seems that the code does not have strict requirements on the exact version of Torch or CUDA, so you can give it a try. Feel free to share your results with me.

Best regards,
Authors
